### ISSUE TITLE
Why not adding fishhook as a cocoapods dependency ?

### ISSUE THREAD

**Issue by deput** [facebook/FBRetainCycleDetector#16]
Some other repo in my project rely on fishhook. Currently build break occurs due to the duplicated fishhook source code.

**Comment by kastiglione** [comment]
Can you paste the build break errors here? The copy of fishhook added to FBRetainCycleDetector was modified to use "`rcd_`" as a prefix on function names to prevent conflicts with other copies of fishhook (which shouldn't have the `rcd_` prefix).

**Comment by deput** [comment]
/Users/yuguo/Work/dev/iphoneapp/Pods/FBRetainCycleDetector/FBRetainCycleDetector/Associations/FBAssociationManager.mm:164:22: Array has incomplete element type 'struct rcd_rebinding'

/Users/yuguo/Work/dev/iphoneapp/Pods/FBRetainCycleDetector/FBRetainCycleDetector/Associations/FBAssociationManager.mm:164:30: Forward declaration of 'rcd_rebinding'

**Comment by deput** [comment]
rename the fishhook.h/c in FBRetainCycleDetector to rcd_fishhook.h/c should solve the issue. Currently I renamed mine as a workaround.

**Comment by kastiglione** [comment]
`FBRetainCycleDetector.podspec` does not expose `fishhook.h` in the public headers. Do your other podspecs put their `fishhook.h` into public headers?

https://github.com/facebook/FBRetainCycleDetector/blob/e777469741343b735d4f6c8febba0edcc2110e00/FBRetainCycleDetector.podspec#L33-L42

**Comment by Megra** [comment]
The fishhook files have been renamed in a recent pull request, this should fix your issue. Closing :)

**Comment by guorenqing** [comment]
My project have the same problem,please release the new version as soon as possible. Thanks!

**Comment by sfmDev** [comment]
Please release the new version. Thanks!
