### ISSUE TITLE
pod validation error

### ISSUE THREAD

**Issue by pingxiasc** [facebook/FBRetainCycleDetector#17]
tried to integrate this lib as a pod. 

but pod spec lint gives the following error

`he following build commands failed:
	CompileC /var/folders/xy/9_l5r2r14cqg8dv46kn4c86w0000gp/T/CocoaPods/Lint/build/Pods.build/Release-iphonesimulator/FBRetainCycleDetector.build/Objects-normal/i386/FBObjectiveCGraphElement.o FBRetainCycleDetector/FBRetainCycleDetector/Graph/FBObjectiveCGraphElement.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
 -> FBRetainCycleDetector (0.1.2)
    - ERROR | [iOS] Returned an unsuccessful exit code.
    - ERROR | [iOS]  FBRetainCycleDetector/FBRetainCycleDetector/Graph/FBObjectiveCGraphElement.m:21:1: error: cannot synthesize weak property in file using manual reference counting
    - NOTE  | [iOS]  FBRetainCycleDetector/FBRetainCycleDetector/Graph/FBObjectiveCGraphElement.h:41:42: note: property declared here

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 2 errors.`

**Comment by Gricha** [comment]
Thank you for flagging, I just bumped the version to `0.1.3` and verified it lints properly. Let me know if you have any further problems.

Thanks!
