### ISSUE TITLE
EXC_BAD_ACCESS while looking for retain cycles using FBRetain+FBAlloction+FBmomey  ，thanks

### ISSUE THREAD

**Issue by davidxwwang** [facebook/FBRetainCycleDetector#22]
![tmp216a209d](https://cloud.githubusercontent.com/assets/13027592/19915442/381f9722-a0ed-11e6-9ed2-d2f30f5f1359.png)

**Comment by Gricha** [comment]
Hey! There is generally some instability involved due to multithreading issues. Are you able to narrow down the issue to specific class it is happening in? Is it a consistent thing?

Since this is happening more than here I'm going to close out the issue. Feel free to reopen with more data.
