### ISSUE TITLE
why the statusBar cycle appear sometime?

### ISSUE THREAD

**Issue by liuzhiyi1992** [facebook/FBRetainCycleDetector#26]
{(
        (
        "-> _statusBar -> UIStatusBar ",
        "-> _statusBarServer -> UIStatusBarServer "
    )
)}

sometime can catch the cycle about statusBar and sometime not?

**Comment by Gricha** [comment]
I am not sure, the implementation of UIStatusBar and how it's held in the application is internal to UIKit I think.

We've seen this retain cycles, but we just ignored them by adding them to ignored section. There are multiple cases of that UIKit cycles, that are technically correct as they will be broken down or won't cause a leak.
