### ISSUE TITLE
NSGetSizeAndAlignment(): unsupported type encoding spec

### ISSUE THREAD

**Issue by niklassaers** [facebook/FBRetainCycleDetector#3]
Hi guys,

In my mixed Swift/ObjC project, I copy/pasted the instructions under "Example usage" into a ObjC file. At

`NSSet *retainCycles = [detector findRetainCycles];`

I got an objc_exception 

> NSGetSizeAndAlignment(): unsupported type encoding spec 'b' at 'b2' in 'b2'

from FBClassStrongLayout.m line 43.

I use FBRetainCycleDetector (0.1.1) via CococaPods (with frameworks enabled)

**Comment by Gricha** [comment]
Hey! Interesting, in general some types are unavailable to query for (for example if you have a struct and this struct has bitfields at the beginning and some objects at the end, we wouldn't cover that).
Because `NSGetSizeAndAlignment()` can throw we have wrapped that in `@try-catch` block.

So that's the idea - the question is - why the exception was not caught. Frameworks might be to blame, I'll look into it a little bit more.

**Comment by Gricha** [comment]
Are you in debug mode? There is a good chance you are not crashing but are stopping in exception breakpoint. Could you try disabling this and check if the issue is still happening for you?

**Comment by kastiglione** [comment]
Yes, the `'b'` is `_C_BFLD`, a bitfield.

Since there's some encoding parsing going on, I wonder if there should be a black list of known bad types, like bitfields, to avoid going down a path that is sure to fail.

**Comment by Gricha** [comment]
That is a good point. Especially that, IIRC, throwing and catching exception is not exactly "free" :P

Maintaining short check-list before falling in might be a good thing for performance, the question is if it's cheaper to sometimes throw & catch, or constantly do a lookup in every ivar check.

Thoughts?

**Comment by JackLSH2016** [comment]
只是路过！

**Comment by HaloWang** [comment]
In my `UIViewController` class, I create a property like this:
`@property (nonatomic, strong) void(^aBlock)();`
and I'm sure there is a retaincycle between my viewController and this property.
When I use FBRetainCycleDetector, I got an objc_exception, like @niklassaers :

> NSGetSizeAndAlignment(): unsupported type encoding spec 'b' at 'b2' in 'b2'

from FBClassStrongLayout.m line 43.

**Comment by Gricha** [comment]
Yes, NSGetSizeAndAlignment throws exception that will be caught by exception breakpoint. The safest is to turn off exception breakpoint when using retain cycle detector.

**Comment by dhcdht** [comment]
```
if (typeEncoding[0] == '^' || typeEncoding[0] == 'b') {
      // It's a pointer or bitfield, let's skip
      size = sizeof(void *);
      align = _Alignof(void *);
}
````
Can we just skip the bitfield type?
