### ISSUE TITLE
crash at NSCAssert

### ISSUE THREAD

**Issue by Quanhua-Guan** [facebook/FBRetainCycleDetector#34]
crash at this line (Xcode 9 beta 5, iOS 11 beta 6)
NSCAssert(nameFromBefore, @"There should always be a name from before if we hit a struct");

**Comment by kastiglione** [comment]
This was fixed in #20, can you try a newer release or master?

**Comment by Quanhua-Guan** [comment]
thanks a lot! @kastiglione
