### ISSUE TITLE
"Segmentation fault: 11" during a compilation or "The LLDB RPC server has crashed" during a runtime

### ISSUE THREAD

**Issue by devcatch** [facebook/FBRetainCycleDetector#35]
I have installed FBRetainCycleDetector by cocoapods.
I successfully created FBRetainCycleDetector and added candidates.

When I try to call findRetainCycles by LLDB I get next 
"The LLDB RPC server has crashed"
`
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.XXXX-gmbh.XXXX        	0x00000001024e0edb _TFC6XXX23XXXX14viewWillAppearfSbT_ + 363 (AnalyticsServiceInterface.swift:137)
1   com.XXXX-gmbh.XXXX        	0x00000001024e0f06 _TToFC6XXXX23XXXX14viewWillAppearfSbT_ + 38
2   com.apple.UIKit               	0x000000010586a2bd -[UIViewController _setViewAppearState:isAnimating:] + 710
3   com.apple.UIKit               	0x000000010586a958 -[UIViewController __viewWillAppear:] + 149
4   com.apple.UIKit               	0x00000001058a9c83 -[UINavigationController _startTransition:fromViewController:toViewController:] + 781
5   com.apple.UIKit               	0x00000001058aac4d -[UINavigationController _startDeferredTransitionIfNeeded:] + 890
6   com.apple.UIKit               	0x00000001058abd0b -[UINavigationController __viewWillLayoutSubviews] + 57
7   com.apple.UIKit               	0x0000000105a5a503 -[UILayoutContainerView layoutSubviews] + 248
8   com.apple.UIKit               	0x0000000105784980 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
9   com.apple.QuartzCore          	0x00000001053d4c00 -[CALayer layoutSublayers] + 146
10  com.apple.QuartzCore          	0x00000001053c908e CA::Layer::layout_if_needed(CA::Transaction*) + 366
11  com.apple.QuartzCore          	0x00000001053c8f0c CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 24
12  com.apple.QuartzCore          	0x00000001053bd3c9 CA::Context::commit_transaction(CA::Transaction*) + 277
13  com.apple.QuartzCore          	0x00000001053eb086 CA::Transaction::commit() + 486
14  com.apple.QuartzCore          	0x00000001053eb7f8 CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
15  com.apple.CoreFoundation      	0x0000000107d37c37 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
16  com.apple.CoreFoundation      	0x0000000107d37ba7 __CFRunLoopDoObservers + 391
17  com.apple.CoreFoundation      	0x0000000107d2d7fb __CFRunLoopRun + 1147
18  com.apple.CoreFoundation      	0x0000000107d2d0f8 CFRunLoopRunSpecific + 488
19  com.apple.GraphicsServices    	0x000000010bd90ad2 GSEventRunModal + 161
20  com.apple.UIKit               	0x00000001056c9f09 UIApplicationMain + 171
21  com.xxxx-gmbh.xxxx        	0x00000001024851e0 main + 48 (AppDelegate.swift:17)
22  libdyld.dylib                 	0x00000001094c592d start + 1`

When I try add a next code:
let cycles = detector.findRetainCycles()
print(cycles)
I get "Segmentation fault: 11" during compilation.

`0  swift                    0x000000010aaaa4f7 PrintStackTraceSignalHandler(void*) + 39
1  swift                    0x000000010aaa99a6 SignalHandler(int) + 646
2  libsystem_platform.dylib 0x00007fffe361fb3a _sigtramp + 26
3  libsystem_platform.dylib 0x00007fff583a8be8 _sigtramp + 1960349896
4  swift                    0x0000000107909c76 swift::irgen::emitArchetypeWitnessTableRef(swift::irgen::IRGenFunction&, swift::CanTypeWrapper<swift::ArchetypeType>, swift::ProtocolDecl*) + 246
5  swift                    0x00000001079f9686 swift::irgen::emitWitnessTableRef(swift::irgen::IRGenFunction&, swift::CanType, llvm::Value**, swift::ProtocolConformanceRef) + 102
6  swift                    0x00000001079f9da0 void llvm::function_ref<void (swift::irgen::GenericRequirement)>::callback_fn<(anonymous namespace)::EmitPolymorphicArguments::emit(swift::CanTypeWrapper<swift::SILFunctionType>, llvm::ArrayRef<swift::Substitution>, swift::irgen::WitnessMetadata*, swift::irgen::Explosion&)::$_14>(long, swift::irgen::GenericRequirement) + 544
7  swift                    0x00000001079f7ce2 void llvm::function_ref<void (swift::irgen::GenericRequirement)>::callback_fn<(anonymous namespace)::PolymorphicConvention::enumerateUnfulfilledRequirements(llvm::function_ref<void (swift::irgen::GenericRequirement)> const&)::$_7>(long, swift::irgen::GenericRequirement) + 162
8  swift                    0x00000001079ef32d (anonymous namespace)::PolymorphicConvention::enumerateRequirements(llvm::function_ref<void (swift::irgen::GenericRequirement)> const&) + 253
9  swift                    0x00000001079f98bf swift::irgen::emitPolymorphicArguments(swift::irgen::IRGenFunction&, swift::CanTypeWrapper<swift::SILFunctionType>, swift::CanTypeWrapper<swift::SILFunctionType>, llvm::ArrayRef<swift::Substitution>, swift::irgen::WitnessMetadata*, swift::irgen::Explosion&) + 431
10 swift                    0x0000000107a5dee5 (anonymous namespace)::IRGenSILFunction::visitFullApplySite(swift::FullApplySite) + 2453
11 swift                    0x0000000107a459ca swift::irgen::IRGenModule::emitSILFunction(swift::SILFunction*) + 9626
12 swift                    0x000000010795d691 swift::irgen::IRGenerator::emitGlobalTopLevel() + 1041
13 swift                    0x0000000107a2c45f performIRGeneration(swift::IRGenOptions&, swift::ModuleDecl*, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule> >, llvm::StringRef, llvm::LLVMContext&, swift::SourceFile*, llvm::GlobalVariable**, unsigned int) + 1695
14 swift                    0x00000001078ca747 swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 51031
15 swift                    0x0000000107877d6c main + 9052
16 libdyld.dylib            0x00007fffe3410235 start + 1`

Did I do something wrong?

**Comment by Megra** [comment]
Sorry for the late answer.
I think a segfault during compilation should be reported to Apple.

If you have a solid repro, file a radar to Apple to let them know if you're compiling using XCode. This can also be reported to Clang/LLVM project directly.

I'm going to close this issue as it's not actionable on our end.
