### ISSUE TITLE
Is This support iOS 11 ?

### ISSUE THREAD

**Issue by ifelseboyxx** [facebook/FBRetainCycleDetector#45]
It's crash in iOS 11:

```
NSCAssert(nameFromBefore, @"There should always be a name from before if we hit a struct");
```

**Comment by TimchenKKBOX** [comment]
Hi, サトシ,
I encountered the same problem.

**Comment by kastiglione** [comment]
That assert and logic was removed a while ago, in #20. Maybe an updated release is what's needed.

**Comment by Megra** [comment]
I've created a new release, make sure to update to it since this issue has been fixed.
We've have been running the latest version successfully at Facebook on iOS11 without any issue.
