### ISSUE TITLE
exception 'NSInternalInconsistencyException'

### ISSUE THREAD

**Issue by lyue1990** [facebook/FBRetainCycleDetector#48]
*** Assertion failure in struct _StructParseResult FB::RetainCycleDetector::Parser::_ParseStructEncodingWithScanner((anonymous namespace)::_StringScanner &)(), /Users/abc/Documents/demo/NewProj/Pods/FBRetainCycleDetector/FBRetainCycleDetector/Layout/Classes/Parser/FBStructEncodingParser.mm:108
2017-11-17 17:38:50.231679+0800 NewProj[13102:533451] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'There should always be a name from before if we hit a struct'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010692a1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010628cf41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010692f362 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x0000000102ed2523 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 165
	4   NewProj                             0x00000001016788b0 _ZN2FB19RetainCycleDetector6ParserL31_ParseStructEncodingWithScannerERN12_GLOBAL__N_114_StringScannerE + 5152
	5   NewProj                             0x00000001016772c1 _ZN2FB19RetainCycleDetector6Parser27parseStructEncodingWithNameERKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEESA_ + 81
	6   NewProj                             0x000000010166c8b1 _ZL41FBGetReferencesForObjectsInStructEncodingP15FBIvarReferenceNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 465
	7   NewProj                             0x000000010166c540 FBGetClassReferences + 512
	8   NewProj                             0x000000010166dae8 _ZL29FBGetStrongReferencesForClassP10objc_class + 24
	9   NewProj                             0x000000010166d970 FBGetObjectStrongReferences + 320
	10  NewProj                             0x0000000101672801 -[FBObjectiveCObject allRetainedObjects] + 369
	11  NewProj                             0x00000001016701c7 -[FBNodeEnumerator nextObject] + 103
	12  NewProj                             0x00000001016740c8 -[FBRetainCycleDetector _findRetainCyclesInObject:stackDepth:] + 472
	13  NewProj                             0x0000000101673cf5 -[FBRetainCycleDetector findRetainCyclesWithMaxCycleLength:] + 437
	14  NewProj                             0x000000010165e9db __95-[FBMemoryProfilerViewController _findRetainCyclesForClassesNamed:inGeneration:presentDetails:]_block_invoke + 1083
	15  libdispatch.dylib                   0x0000000106e9a3f7 _dispatch_call_block_and_release + 12
	16  libdispatch.dylib                   0x0000000106e9b43c _dispatch_client_callout + 8
	17  libdispatch.dylib                   0x0000000106ea0352 _dispatch_queue_override_invoke + 1458
	18  libdispatch.dylib                   0x0000000106ea71f9 _dispatch_root_queue_drain + 772
	19  libdispatch.dylib                   0x0000000106ea6e97 _dispatch_worker_thread3 + 132
	20  libsystem_pthread.dylib             0x000000010735e5a2 _pthread_wqthread + 1299
	21  libsystem_pthread.dylib             0x000000010735e07d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by lyue1990** [comment]
I can not find the solution, anyone know it?

**Comment by Megra** [comment]
I think you are using an older version, can you try updating to the latest revision, pulling from master and see if it still reproduces?
