### ISSUE TITLE
https://github.com/facebook/FBRetainCycleDetector/blob/84bc82b951c5a16b2d62222ce51993cc8abc5993/FBRetainCycleDetectorTests/FBAssociationManagerTests.mm#L10

### ISSUE THREAD

**Issue by caschomburg123** [facebook/FBRetainCycleDetector#51]
https://github.com/facebook/FBRetainCycleDetector/blob/84bc82b951c5a16b2d62222ce51993cc8abc5993/FBRetainCycleDetectorTests/FBAssociationManagerTests.mm#L10

**Comment by Megra** [comment]
I'm not sure what this issue is about, I will close it. 
Feel free to re-open with more information.
