### ISSUE TITLE
about private APIs in `FBRetainCycleDetector`

### ISSUE THREAD

**Issue by Yincongxiao** [facebook/FBRetainCycleDetector#78]
hi, I see the comment before the macro `RETAIN_CYCLE_DETECTOR_ENABLED` in file `FBRetainCycleDetector.h`

```
/**
 Retain Cycle Detector is enabled by default in DEBUG builds, but you can also force it in other builds by
 uncommenting the line below. Beware, Retain Cycle Detector uses some private APIs that shouldn't be compiled in
 production builds.
 */
```

I want use `FBRetainCycleDetector` in production environment to find retain cycles, so I want know what `Private APIs` of FBR use.
thanks a lot!

**Comment by youngdfb** [comment]
Hello, FBRetainCycleDetecotr uses [FishHook](https://github.com/facebook/react-native/tree/master/Libraries/fishhook), which rebinds symbols.  This is unlikely something Apple would allow in a production build.

**Comment by Yincongxiao** [comment]
> Hello, FBRetainCycleDetecotr uses [FishHook](https://github.com/facebook/react-native/tree/master/Libraries/fishhook), which rebinds symbols. This is unlikely something Apple would allow in a production build.

I think the `Fishhook` is not the sensitive point, because it is in my productive app.
