### ISSUE TITLE
iOS 13 FBRetainCycleDetector crash when open Guided Access

### ISSUE THREAD

**Issue by CmST0us** [facebook/FBRetainCycleDetector#81]
In iOS 13, when I turn on Guided Access switch in Accessibility (just turn on the switch, not enter Guided Access in app), the FBRetainCycleDetector will crash in starting time.
It's easy to reappear.

**Comment by youngdfb** [comment]
Could you let us know which iPhone you were using?  And also which beta version of iOS 13 (it seems that beta 6 launch today or yesterday)?

**Comment by CmST0us** [comment]
> Could you let us know which iPhone you were using? And also which beta version of iOS 13 (it seems that beta 6 launch today or yesterday)?

My device is iPhone XR, and I just tested in iOS 13 beta6, it crashed again!

**Comment by youngdfb** [comment]
Thanks for the update!  Just wanted to be sure it wasn't an old beta version.  We will attempt to replicate this on our side. 
Turning on the same accessibility option in iOS 12 didn't cause this?
Also, does this only reproduce on a device running iOS 13 or have you managed it with the next XCode beta (of which beta 5 is the latest when I checked yesterday)

**Comment by CmST0us** [comment]
> Thanks for the update! Just wanted to be sure it wasn't an old beta version. We will attempt to replicate this on our side.
> Turning on the same accessibility option in iOS 12 didn't cause this?
> Also, does this only reproduce on a device running iOS 13 or have you managed it with the next XCode beta (of which beta 5 is the latest when I checked yesterday)

Thanks!
I have try in iOS12.4, it didn't crash. It looks like this problem only happen in iOS 13. And I build my app with Xcode 11 beta5.
BTW: I use Debug building configuration.

**Comment by youngdfb** [comment]
Thanks for all the information!  After we can repro or get a fix, we will let you know

**Comment by youngdfb** [comment]
There has been a commit synced from Facebook's Fishhook repository: https://github.com/facebook/FBRetainCycleDetector/commit/c3d5fb93768267f542acaf570fe0b0c01e789389
This was an issue specific to iOS 13.  Could you please pull the latest and let us know if your issue is resolved?  Thanks!

**Comment by CmST0us** [comment]
> There has been a commit synced from Facebook's Fishhook repository: [c3d5fb9](https://github.com/facebook/FBRetainCycleDetector/commit/c3d5fb93768267f542acaf570fe0b0c01e789389)
> This was an issue specific to iOS 13. Could you please pull the latest and let us know if your issue is resolved? Thanks!

YES! It works!
Thank you very much!

**Comment by ThaiLanKing** [comment]
It happend on iPhone XR(iOS13.1),anohter iPhone6s(iOS13.1) is OK,and crash here:indirect_symbol_bindings[i] = cur->rebindings[j].replacement;
